-- Test-only baseline for tables that existed before this repository started
-- tracking database migrations. This file intentionally contains schema only
-- and must never be applied to an existing/production database.

CREATE TYPE public.visita_status AS ENUM (
  'pendente',
  'realizada',
  'ausente',
  'cancelada'
);

CREATE TABLE public.encontros (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  nome text NOT NULL,
  data_inicio date NOT NULL,
  data_fim date NOT NULL,
  local text,
  descricao text,
  ativo boolean DEFAULT false,
  created_at timestamptz DEFAULT now(),
  edicao bigint UNIQUE,
  tema text,
  musica text,
  link_musica text,
  link_youtube text,
  valor_taxa numeric DEFAULT 0
);

CREATE TABLE public.equipes (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at timestamptz NOT NULL DEFAULT now(),
  nome text,
  deleted_at timestamp
);

CREATE TABLE public.pessoas (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  nome_completo text NOT NULL,
  cpf text UNIQUE,
  email text,
  telefone text,
  comunidade text,
  data_nascimento date,
  qr_code_token uuid UNIQUE,
  created_at timestamptz DEFAULT now(),
  nome_pai text,
  nome_mae text,
  endereco text,
  numero text,
  bairro text,
  cidade text,
  telefone_pai text,
  telefone_mae text,
  outros_contatos text,
  fez_ejc_outra_paroquia boolean DEFAULT false,
  qual_paroquia_ejc text,
  latitude numeric,
  longitude numeric,
  complemento text
);

CREATE TABLE public.participacoes (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  pessoa_id uuid NOT NULL REFERENCES public.pessoas(id) ON DELETE RESTRICT,
  encontro_id uuid NOT NULL REFERENCES public.encontros(id) ON DELETE CASCADE,
  data_inscricao timestamptz DEFAULT now(),
  participante boolean,
  equipe_id uuid REFERENCES public.equipes(id) ON DELETE RESTRICT,
  coordenador boolean,
  dados_confirmados boolean DEFAULT false,
  confirmado_em timestamptz,
  pago_taxa boolean DEFAULT false,
  UNIQUE (pessoa_id, encontro_id)
);

-- Compatibility objects used by same-day migrations whose legacy filenames
-- do not encode a deterministic time order.
CREATE TABLE public.external_sessions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  participacao_id uuid NOT NULL REFERENCES public.participacoes(id) ON DELETE CASCADE,
  encontro_id uuid NOT NULL REFERENCES public.encontros(id) ON DELETE CASCADE,
  token uuid NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  expires_at timestamptz NOT NULL,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE public.external_access_attempts (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  ip_address text,
  last_attempt timestamptz DEFAULT now(),
  attempts_count integer DEFAULT 1
);

CREATE TABLE public.circulos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  nome text,
  deleted_at timestamp
);

CREATE TABLE public.circulo_participacao (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at timestamptz NOT NULL DEFAULT now(),
  circulo_id bigint REFERENCES public.circulos(id) ON DELETE RESTRICT,
  participacao uuid NOT NULL REFERENCES public.participacoes(id) ON DELETE RESTRICT,
  mediador boolean
);

CREATE TABLE public.visita_grupos (
  id uuid PRIMARY KEY DEFAULT extensions.uuid_generate_v4(),
  encontro_id uuid REFERENCES public.encontros(id) ON DELETE CASCADE,
  nome text,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE public.visita_participacao (
  id uuid PRIMARY KEY DEFAULT extensions.uuid_generate_v4(),
  grupo_id uuid REFERENCES public.visita_grupos(id) ON DELETE RESTRICT,
  participacao_id uuid REFERENCES public.participacoes(id) ON DELETE RESTRICT,
  visitante boolean DEFAULT false,
  created_at timestamptz DEFAULT now(),
  status public.visita_status DEFAULT 'pendente',
  observacoes text,
  foto_url text,
  taxa_paga boolean DEFAULT false,
  data_visita timestamptz
);

CREATE TABLE public.lista_espera (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  nome_completo text NOT NULL,
  email text,
  telefone text NOT NULL,
  data_nascimento date,
  criado_em timestamptz DEFAULT now(),
  created_at timestamptz DEFAULT now()
);

CREATE TABLE public.galeria (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  retiro_id uuid NOT NULL REFERENCES public.encontros(id) ON DELETE CASCADE,
  url text NOT NULL,
  titulo text,
  descricao text,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE public.configuracoes_exportacao (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  titulo text,
  subtitulo text,
  tema text,
  imagem_esq_base64 text,
  imagem_dir_base64 text,
  observacoes text,
  config_telas jsonb DEFAULT '{}'::jsonb,
  created_at timestamptz DEFAULT timezone('utc', now()),
  updated_at timestamptz DEFAULT timezone('utc', now()),
  encontro_id uuid REFERENCES public.encontros(id)
);

CREATE TABLE public.camiseta_modelos (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  nome text NOT NULL UNIQUE,
  ativo boolean DEFAULT true,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE public.camiseta_pedidos (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  participacao_id uuid NOT NULL REFERENCES public.participacoes(id) ON DELETE CASCADE,
  modelo_id uuid NOT NULL REFERENCES public.camiseta_modelos(id),
  tamanho text NOT NULL,
  quantidade integer NOT NULL DEFAULT 1,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE public.camiseta_config_encontro (
  id uuid PRIMARY KEY DEFAULT extensions.uuid_generate_v4(),
  encontro_id uuid NOT NULL REFERENCES public.encontros(id) ON DELETE CASCADE,
  modelo_id uuid NOT NULL REFERENCES public.camiseta_modelos(id) ON DELETE CASCADE,
  valor numeric(10, 2) NOT NULL DEFAULT 0,
  ativo boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (encontro_id, modelo_id)
);
