-- Caixa de entrada institucional: metadados leves no Postgres; conteúdo e
-- anexos permanecem privados no Cloudflare R2.

INSERT INTO public.permissoes (chave, nome, descricao)
VALUES
  ('modulo_email_institucional', 'E-mail institucional', 'Visualizar a caixa de entrada institucional'),
  ('email_institucional_responder', 'Responder e-mail institucional', 'Responder e alterar o atendimento de mensagens institucionais'),
  ('email_institucional_gerenciar', 'Gerenciar e-mail institucional', 'Gerenciar responsáveis e excluir mensagens institucionais')
ON CONFLICT (chave) DO UPDATE SET
  nome = EXCLUDED.nome,
  descricao = EXCLUDED.descricao;

INSERT INTO public.grupo_permissoes (grupo_id, permissao_id)
SELECT grupo.id, permissao.id
FROM public.grupos grupo
CROSS JOIN public.permissoes permissao
WHERE grupo.nome = 'Administrador'
  AND permissao.chave IN (
    'modulo_email_institucional',
    'email_institucional_responder',
    'email_institucional_gerenciar'
  )
ON CONFLICT DO NOTHING;

CREATE TABLE public.email_institucional_conversas (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  assunto text NOT NULL DEFAULT '(sem assunto)',
  contato_email text NOT NULL,
  contato_nome text,
  status text NOT NULL DEFAULT 'novo'
    CHECK (status IN ('novo', 'em_atendimento', 'resolvido')),
  responsavel_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  ultima_mensagem_em timestamptz NOT NULL DEFAULT now(),
  criada_em timestamptz NOT NULL DEFAULT now(),
  atualizada_em timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.email_institucional_mensagens (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  conversa_id uuid NOT NULL REFERENCES public.email_institucional_conversas(id) ON DELETE CASCADE,
  direcao text NOT NULL CHECK (direcao IN ('entrada', 'saida')),
  provider_message_id text,
  in_reply_to text,
  references_header text,
  remetente_email text NOT NULL,
  remetente_nome text,
  destinatarios text[] NOT NULL DEFAULT '{}',
  copias text[] NOT NULL DEFAULT '{}',
  assunto text NOT NULL DEFAULT '(sem assunto)',
  previa text NOT NULL DEFAULT '',
  r2_texto_key text,
  r2_html_key text,
  r2_raw_key text,
  tamanho_bytes bigint NOT NULL DEFAULT 0 CHECK (tamanho_bytes >= 0),
  status_envio text CHECK (status_envio IS NULL OR status_envio IN ('enviando', 'enviado', 'falhou')),
  erro_envio text,
  criado_por uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  recebida_em timestamptz,
  enviada_em timestamptz,
  criada_em timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT email_institucional_mensagens_provider_unique UNIQUE (provider_message_id)
);

CREATE TABLE public.email_institucional_anexos (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  mensagem_id uuid NOT NULL REFERENCES public.email_institucional_mensagens(id) ON DELETE CASCADE,
  nome text NOT NULL,
  mime_type text NOT NULL DEFAULT 'application/octet-stream',
  tamanho_bytes bigint NOT NULL CHECK (tamanho_bytes >= 0),
  content_id text,
  r2_key text NOT NULL UNIQUE,
  criada_em timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.email_institucional_leituras (
  conversa_id uuid NOT NULL REFERENCES public.email_institucional_conversas(id) ON DELETE CASCADE,
  usuario_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  lida_ate timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (conversa_id, usuario_id)
);

CREATE TABLE public.email_institucional_eventos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conversa_id uuid NOT NULL REFERENCES public.email_institucional_conversas(id) ON DELETE CASCADE,
  mensagem_id uuid REFERENCES public.email_institucional_mensagens(id) ON DELETE SET NULL,
  usuario_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  tipo text NOT NULL CHECK (tipo IN ('recebida', 'lida', 'status_alterado', 'responsavel_alterado', 'resposta_enviada', 'resposta_falhou', 'anexo_baixado', 'excluida')),
  detalhes jsonb NOT NULL DEFAULT '{}'::jsonb,
  criado_em timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX email_institucional_conversas_ultima_idx
  ON public.email_institucional_conversas (ultima_mensagem_em DESC);
CREATE INDEX email_institucional_conversas_status_idx
  ON public.email_institucional_conversas (status, ultima_mensagem_em DESC);
CREATE INDEX email_institucional_mensagens_conversa_idx
  ON public.email_institucional_mensagens (conversa_id, criada_em);
CREATE INDEX email_institucional_eventos_conversa_idx
  ON public.email_institucional_eventos (conversa_id, criado_em DESC);

CREATE OR REPLACE FUNCTION public.pode_visualizar_email_institucional(
  check_user uuid DEFAULT auth.uid()
)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT check_user IS NOT NULL AND (
    public.is_admin(check_user)
    OR public.has_permission(check_user, 'modulo_email_institucional')
  );
$$;

CREATE OR REPLACE FUNCTION public.pode_responder_email_institucional(
  check_user uuid DEFAULT auth.uid()
)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT check_user IS NOT NULL AND (
    public.is_admin(check_user)
    OR public.has_permission(check_user, 'email_institucional_responder')
  );
$$;

CREATE OR REPLACE FUNCTION public.marcar_email_institucional_como_lido(
  p_conversa_id uuid
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF NOT public.pode_visualizar_email_institucional(auth.uid()) THEN
    RAISE EXCEPTION 'Acesso não autorizado.' USING ERRCODE = '42501';
  END IF;

  INSERT INTO public.email_institucional_leituras (conversa_id, usuario_id, lida_ate)
  VALUES (p_conversa_id, auth.uid(), now())
  ON CONFLICT (conversa_id, usuario_id)
  DO UPDATE SET lida_ate = EXCLUDED.lida_ate;

  INSERT INTO public.email_institucional_eventos (conversa_id, usuario_id, tipo)
  VALUES (p_conversa_id, auth.uid(), 'lida');
END;
$$;

CREATE OR REPLACE FUNCTION public.atualizar_atendimento_email_institucional(
  p_conversa_id uuid,
  p_status text DEFAULT NULL,
  p_responsavel_id uuid DEFAULT NULL,
  p_alterar_responsavel boolean DEFAULT false
)
RETURNS public.email_institucional_conversas
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_anterior public.email_institucional_conversas;
  v_atual public.email_institucional_conversas;
BEGIN
  IF NOT public.pode_responder_email_institucional(auth.uid()) THEN
    RAISE EXCEPTION 'Acesso não autorizado.' USING ERRCODE = '42501';
  END IF;

  IF p_status IS NOT NULL AND p_status NOT IN ('novo', 'em_atendimento', 'resolvido') THEN
    RAISE EXCEPTION 'Status inválido.' USING ERRCODE = '22023';
  END IF;

  SELECT * INTO v_anterior
  FROM public.email_institucional_conversas
  WHERE id = p_conversa_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Conversa não encontrada.' USING ERRCODE = 'P0002';
  END IF;

  UPDATE public.email_institucional_conversas
  SET status = COALESCE(p_status, status),
      responsavel_id = CASE WHEN p_alterar_responsavel THEN p_responsavel_id ELSE responsavel_id END,
      atualizada_em = now()
  WHERE id = p_conversa_id
  RETURNING * INTO v_atual;

  IF p_status IS NOT NULL AND p_status IS DISTINCT FROM v_anterior.status THEN
    INSERT INTO public.email_institucional_eventos (conversa_id, usuario_id, tipo, detalhes)
    VALUES (p_conversa_id, auth.uid(), 'status_alterado', jsonb_build_object('de', v_anterior.status, 'para', p_status));
  END IF;

  IF p_alterar_responsavel AND p_responsavel_id IS DISTINCT FROM v_anterior.responsavel_id THEN
    INSERT INTO public.email_institucional_eventos (conversa_id, usuario_id, tipo, detalhes)
    VALUES (p_conversa_id, auth.uid(), 'responsavel_alterado', jsonb_build_object('de', v_anterior.responsavel_id, 'para', p_responsavel_id));
  END IF;

  RETURN v_atual;
END;
$$;

CREATE OR REPLACE FUNCTION public.listar_email_institucional_conversas(
  p_busca text DEFAULT NULL,
  p_status text DEFAULT NULL,
  p_limite integer DEFAULT 50,
  p_offset integer DEFAULT 0
)
RETURNS TABLE (
  id uuid,
  assunto text,
  contato_email text,
  contato_nome text,
  status text,
  responsavel_id uuid,
  responsavel_nome text,
  ultima_mensagem_em timestamptz,
  ultima_previa text,
  ultima_direcao text,
  nao_lida boolean
)
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF NOT public.pode_visualizar_email_institucional(auth.uid()) THEN
    RAISE EXCEPTION 'Acesso não autorizado.' USING ERRCODE = '42501';
  END IF;

  RETURN QUERY
  SELECT
    conversa.id,
    conversa.assunto,
    conversa.contato_email,
    conversa.contato_nome,
    conversa.status,
    conversa.responsavel_id,
    COALESCE(responsavel_pessoa.nome_completo, responsavel.email),
    conversa.ultima_mensagem_em,
    ultima.previa,
    ultima.direcao,
    COALESCE(leitura.lida_ate < conversa.ultima_mensagem_em, true)
      AND ultima.direcao = 'entrada' AS nao_lida
  FROM public.email_institucional_conversas conversa
  LEFT JOIN public.profiles responsavel ON responsavel.id = conversa.responsavel_id
  LEFT JOIN public.pessoas responsavel_pessoa ON responsavel_pessoa.id = responsavel.pessoa_id
  LEFT JOIN public.email_institucional_leituras leitura
    ON leitura.conversa_id = conversa.id AND leitura.usuario_id = auth.uid()
  LEFT JOIN LATERAL (
    SELECT mensagem.previa, mensagem.direcao
    FROM public.email_institucional_mensagens mensagem
    WHERE mensagem.conversa_id = conversa.id
    ORDER BY mensagem.criada_em DESC
    LIMIT 1
  ) ultima ON true
  WHERE (p_status IS NULL OR conversa.status = p_status)
    AND (
      NULLIF(trim(p_busca), '') IS NULL
      OR conversa.assunto ILIKE '%' || trim(p_busca) || '%'
      OR conversa.contato_email ILIKE '%' || trim(p_busca) || '%'
      OR COALESCE(conversa.contato_nome, '') ILIKE '%' || trim(p_busca) || '%'
      OR COALESCE(ultima.previa, '') ILIKE '%' || trim(p_busca) || '%'
    )
  ORDER BY conversa.ultima_mensagem_em DESC
  LIMIT LEAST(GREATEST(p_limite, 1), 100)
  OFFSET GREATEST(p_offset, 0);
END;
$$;

CREATE OR REPLACE FUNCTION public.registrar_download_email_institucional(
  p_anexo_id uuid
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_conversa_id uuid;
  v_mensagem_id uuid;
BEGIN
  IF NOT public.pode_visualizar_email_institucional(auth.uid()) THEN
    RAISE EXCEPTION 'Acesso não autorizado.' USING ERRCODE = '42501';
  END IF;

  SELECT mensagem.conversa_id, anexo.mensagem_id
  INTO v_conversa_id, v_mensagem_id
  FROM public.email_institucional_anexos anexo
  JOIN public.email_institucional_mensagens mensagem ON mensagem.id = anexo.mensagem_id
  WHERE anexo.id = p_anexo_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Anexo não encontrado.' USING ERRCODE = 'P0002';
  END IF;

  INSERT INTO public.email_institucional_eventos (
    conversa_id, mensagem_id, usuario_id, tipo, detalhes
  )
  VALUES (
    v_conversa_id, v_mensagem_id, auth.uid(), 'anexo_baixado',
    jsonb_build_object('anexo_id', p_anexo_id)
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.registrar_email_institucional_recebido(
  p_dados jsonb
)
RETURNS uuid
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_conversa_id uuid;
  v_mensagem_id uuid := (p_dados ->> 'id')::uuid;
  v_provider_message_id text := NULLIF(p_dados ->> 'provider_message_id', '');
  v_anexo jsonb;
BEGIN
  IF v_provider_message_id IS NOT NULL THEN
    SELECT mensagem.conversa_id INTO v_conversa_id
    FROM public.email_institucional_mensagens mensagem
    WHERE mensagem.provider_message_id = v_provider_message_id;
    IF FOUND THEN RETURN v_conversa_id; END IF;
  END IF;

  v_conversa_id := NULLIF(p_dados ->> 'conversa_id', '')::uuid;
  IF v_conversa_id IS NULL OR NOT EXISTS (
    SELECT 1 FROM public.email_institucional_conversas WHERE id = v_conversa_id
  ) THEN
    INSERT INTO public.email_institucional_conversas (
      assunto, contato_email, contato_nome, status, ultima_mensagem_em
    )
    VALUES (
      COALESCE(NULLIF(p_dados ->> 'assunto_conversa', ''), '(sem assunto)'),
      lower(p_dados ->> 'remetente_email'),
      NULLIF(p_dados ->> 'remetente_nome', ''),
      'novo',
      COALESCE((p_dados ->> 'recebida_em')::timestamptz, now())
    )
    RETURNING id INTO v_conversa_id;
  END IF;

  INSERT INTO public.email_institucional_mensagens (
    id, conversa_id, direcao, provider_message_id, in_reply_to,
    references_header, remetente_email, remetente_nome, destinatarios,
    copias, assunto, previa, r2_texto_key, r2_html_key, r2_raw_key,
    tamanho_bytes, recebida_em
  )
  VALUES (
    v_mensagem_id,
    v_conversa_id,
    'entrada',
    v_provider_message_id,
    NULLIF(p_dados ->> 'in_reply_to', ''),
    NULLIF(p_dados ->> 'references_header', ''),
    lower(p_dados ->> 'remetente_email'),
    NULLIF(p_dados ->> 'remetente_nome', ''),
    ARRAY(SELECT jsonb_array_elements_text(COALESCE(p_dados -> 'destinatarios', '[]'::jsonb))),
    ARRAY(SELECT jsonb_array_elements_text(COALESCE(p_dados -> 'copias', '[]'::jsonb))),
    COALESCE(NULLIF(p_dados ->> 'assunto', ''), '(sem assunto)'),
    left(COALESCE(p_dados ->> 'previa', ''), 500),
    NULLIF(p_dados ->> 'r2_texto_key', ''),
    NULLIF(p_dados ->> 'r2_html_key', ''),
    NULLIF(p_dados ->> 'r2_raw_key', ''),
    GREATEST(COALESCE((p_dados ->> 'tamanho_bytes')::bigint, 0), 0),
    COALESCE((p_dados ->> 'recebida_em')::timestamptz, now())
  );

  FOR v_anexo IN SELECT value FROM jsonb_array_elements(COALESCE(p_dados -> 'anexos', '[]'::jsonb))
  LOOP
    INSERT INTO public.email_institucional_anexos (
      id, mensagem_id, nome, mime_type, tamanho_bytes, content_id, r2_key
    )
    VALUES (
      (v_anexo ->> 'id')::uuid,
      v_mensagem_id,
      COALESCE(NULLIF(v_anexo ->> 'nome', ''), 'anexo'),
      COALESCE(NULLIF(v_anexo ->> 'mime_type', ''), 'application/octet-stream'),
      GREATEST(COALESCE((v_anexo ->> 'tamanho_bytes')::bigint, 0), 0),
      NULLIF(v_anexo ->> 'content_id', ''),
      v_anexo ->> 'r2_key'
    );
  END LOOP;

  UPDATE public.email_institucional_conversas
  SET status = 'novo',
      ultima_mensagem_em = COALESCE((p_dados ->> 'recebida_em')::timestamptz, now()),
      atualizada_em = now()
  WHERE id = v_conversa_id;

  INSERT INTO public.email_institucional_eventos (conversa_id, mensagem_id, tipo)
  VALUES (v_conversa_id, v_mensagem_id, 'recebida');

  RETURN v_conversa_id;
END;
$$;

ALTER TABLE public.email_institucional_conversas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.email_institucional_mensagens ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.email_institucional_anexos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.email_institucional_leituras ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.email_institucional_eventos ENABLE ROW LEVEL SECURITY;

CREATE POLICY email_institucional_conversas_select
  ON public.email_institucional_conversas FOR SELECT TO authenticated
  USING (public.pode_visualizar_email_institucional(auth.uid()));
CREATE POLICY email_institucional_mensagens_select
  ON public.email_institucional_mensagens FOR SELECT TO authenticated
  USING (public.pode_visualizar_email_institucional(auth.uid()));
CREATE POLICY email_institucional_anexos_select
  ON public.email_institucional_anexos FOR SELECT TO authenticated
  USING (public.pode_visualizar_email_institucional(auth.uid()));
CREATE POLICY email_institucional_leituras_select
  ON public.email_institucional_leituras FOR SELECT TO authenticated
  USING (public.pode_visualizar_email_institucional(auth.uid()));
CREATE POLICY email_institucional_eventos_select
  ON public.email_institucional_eventos FOR SELECT TO authenticated
  USING (public.pode_visualizar_email_institucional(auth.uid()));

REVOKE ALL ON TABLE public.email_institucional_conversas FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public.email_institucional_mensagens FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public.email_institucional_anexos FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public.email_institucional_leituras FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public.email_institucional_eventos FROM PUBLIC, anon, authenticated;
GRANT SELECT ON TABLE public.email_institucional_conversas TO authenticated;
GRANT SELECT ON TABLE public.email_institucional_mensagens TO authenticated;
GRANT SELECT ON TABLE public.email_institucional_anexos TO authenticated;
GRANT SELECT ON TABLE public.email_institucional_leituras TO authenticated;
GRANT SELECT ON TABLE public.email_institucional_eventos TO authenticated;
GRANT ALL ON TABLE public.email_institucional_conversas TO service_role;
GRANT ALL ON TABLE public.email_institucional_mensagens TO service_role;
GRANT ALL ON TABLE public.email_institucional_anexos TO service_role;
GRANT ALL ON TABLE public.email_institucional_leituras TO service_role;
GRANT ALL ON TABLE public.email_institucional_eventos TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.email_institucional_eventos_id_seq TO service_role;

REVOKE ALL ON FUNCTION public.pode_visualizar_email_institucional(uuid) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.pode_responder_email_institucional(uuid) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.marcar_email_institucional_como_lido(uuid) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.atualizar_atendimento_email_institucional(uuid, text, uuid, boolean) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.listar_email_institucional_conversas(text, text, integer, integer) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.registrar_download_email_institucional(uuid) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.registrar_email_institucional_recebido(jsonb) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.pode_visualizar_email_institucional(uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.pode_responder_email_institucional(uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.marcar_email_institucional_como_lido(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.atualizar_atendimento_email_institucional(uuid, text, uuid, boolean) TO authenticated;
GRANT EXECUTE ON FUNCTION public.listar_email_institucional_conversas(text, text, integer, integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.registrar_download_email_institucional(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.registrar_email_institucional_recebido(jsonb) TO service_role;

ALTER PUBLICATION supabase_realtime ADD TABLE public.email_institucional_conversas;
ALTER PUBLICATION supabase_realtime ADD TABLE public.email_institucional_mensagens;

COMMENT ON TABLE public.email_institucional_mensagens IS
  'Índice leve da caixa institucional. Corpos completos e MIME ficam privados no R2.';
